<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:35px;color:  #c1531f   ">ML Zoomcamp Session 1 Homework Questions</li>

<div class="alert alert-info" role="alert" style="font-family:cursive;font-size:15px;color:  #2025bd">

<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Question 1:</u></p>
<ul>
<li>What's the version of NumPy that you installed?</li>
</ul>
    
<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Question 2:</u></p>
<ul>
<li>What's the version of Pandas?</li>
</ul>    
    
<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Question 3:</u></p>
<ul>
<li>What's the average price of BMW cars in the dataset?</li>
</ul>  
    
<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Question 4:</u></p>
<ul>
<li>Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?</li>
</ul> 

<p style="font-family:cursive;font-size:15px;color:  #2025bd"> <u>Question 5: </u></p>
<ul>
<li>Calculate the average "Engine HP" in the dataset.</li>
<li>Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.</li>
<li> Now, calcualte the average of "Engine HP" again.</li>
<li> Has it changed?</li>
<li> Round both means before answering this questions. You can use the round function for that:</li>
<code style="font-family:cursive;font-size:15px;color:  #2025bd">print(round(mean_hp_before))</code>
<code style="font-family:cursive;font-size:15px;color:  #2025bd">print(round(mean_hp_after))</code></ul>
    
<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Question 6:</u></p> 
<ul>
<li>Select all the "Rolls-Royce" cars from the dataset.</li>
<li>Select only columns "Engine HP", "Engine Cylinders", "highway MPG".</li>
<li>Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).</li>
<li>Get the underlying NumPy array. Let's call it X.</li>
<li>Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.</li>
<li>Invert XTX.</li>
<li>What's the sum of all the elements of the result?</li>
    <u>Hint: if the result is negative, re-read the task one more time</u>
</ul>
    
<p style="font-family:cursive;font-size:15px;color:  #2025bd"><u>Questions 7</u></p>
<ul>
<li>Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].</li>
<li>Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.</li>
<li>What's the value of the first element of w?.</li>
    <u>Note: You just implemented linear regression. We'll talk about it in the next lesson.</u>
    </ul>
            


</div>

- **https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
                                   Dataset for Homework

<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:35px;color:  #c1531f   ">Importing Required Libraries</li>

In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:35px;color:  #c1531f   ">Loading Data</li>

In [2]:
df = pd.read_csv('../input/homework-1-data/data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   ">Question 1</li>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>1. What's the version of NumPy that you installed?</li>
    </ul>


In [3]:
np.__version__

'1.19.5'

<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   ">Question 2</li>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>What's the version of Pandas?</li>
    </ul>

In [4]:
pd.__version__

'1.3.2'

<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   ">Question 3</li>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>What's the average price of BMW cars in the dataset?</li>
    </ul>

In [5]:
print("average price of BMW cars in the dataset: ",round(np.mean(df[df['Make'] == 'BMW']['MSRP']), 2))

average price of BMW cars in the dataset:  61546.76


<li style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   ">Question 4</li>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?</li>
    </ul>

In [6]:
display(df[df['Year'] >= 2015].isnull().sum().to_frame().reset_index().rename({'index': 'Variables', 0: 'Missing Values'}, axis = 1).sort_values(by = 'Missing Values',ascending = False).head(2).style.background_gradient(cmap = 'Blues_r'))
print("Missing Values in Variable Engine HP: ", df[df['Year'] >= 2015]['Engine HP'].isnull().sum())

Missing Values in Variable Engine HP:  51


<p style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   "> <u>Question 5: </u></p>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>Calculate the average "Engine HP" in the dataset.</li>
<li>Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.</li>
<li> Now, calcualte the average of "Engine HP" again.</li>
<li> Has it changed?</li>
<li> Round both means before answering this questions. You can use the round function for that:</li>
<code style="font-family:cursive;font-size:15px;color:  #2025bd">print(round(mean_hp_before))</code>
<code style="font-family:cursive;font-size:15px;color:  #2025bd">print(round(mean_hp_after))</code></ul>
    

In [7]:
"""
Calculate the average "Engine HP" in the dataset.
Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
"""
mean_hp_before =  df['Engine HP'].mean()
print("Mean of Engine HP BEFORE Imputing Missing Values", round(mean_hp_before,2))
df['Engine HP'].fillna(mean_hp_before, inplace=True)

Mean of Engine HP BEFORE Imputing Missing Values 249.39


In [8]:
"""
Now, calcualte the average of "Engine HP" again.
Has it changed?
Round both means before answering this questions. You can use the round function for that.
"""
mean_hp_after = df['Engine HP'].mean()
print("Mean of Engine HP BEFORE Imputing Missing Values", round(mean_hp_before,2))
print("Mean of Engine HP AFTER Imputing Missing Values", round(mean_hp_after,2))

Mean of Engine HP BEFORE Imputing Missing Values 249.39
Mean of Engine HP AFTER Imputing Missing Values 249.39


<p style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   "> <u>Question 6: </u></p>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>Select all the "Rolls-Royce" cars from the dataset.</li>
<li>Select only columns "Engine HP", "Engine Cylinders", "highway MPG".</li>
<li>Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).</li>
<li>Get the underlying NumPy array. Let's call it X.</li>
<li>Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.</li>
<li>Invert XTX.</li>
<li>What's the sum of all the elements of the result?</li>
    <u>Hint: if the result is negative, re-read the task one more time</u>
</ul>

In [9]:
"""
Select all the "Rolls-Royce" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
"""
df[df['Make'] == 'Rolls-Royce'][["Engine HP","Engine Cylinders", "highway MPG"]].drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [10]:
"""
Get the underlying NumPy array. Let's call it X.
"""
X = np.array(df[df['Make'] == 'Rolls-Royce'][["Engine HP","Engine Cylinders", "highway MPG"]].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [11]:
"""
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
"""
XTX=(X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [12]:
"""
Invert XTX.
"""
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [13]:
"""
What's the sum of all the elements of the result?
"""
print("sum of all the elements of the result: ",XTX_inv.sum())

sum of all the elements of the result:  0.032212320677486125


<p style="font-family:'Goudy Old Style';font-weight: bold;font-size:30px;color:  #c1531f   "> <u>Question 7: </u></p>
<ul style="font-family:cursive;font-size:15px;color:  #2025bd">
<li>Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].</li>
<li>Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.</li>
<li>What's the value of the first element of w?.</li>
    <u>Note: You just implemented linear regression. We'll talk about it in the next lesson.</u>
    </ul>

In [14]:
"""
Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]
"""
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [15]:
"""
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
"""
w = ((np.linalg.inv(XTX)).dot(X.T)).dot(y)

In [16]:
"""
What's the value of the first element of w?
"""
print("Value of the first element of w: ", w[0])

Value of the first element of w:  0.19989598183188972
