# Numpy
- **NumPy (or Numpy) is a Linear Algebra Library for Python**
- **Almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.**
- **Numpy is also incredibly fast beacuse of its bindings to C libraries.**
<p>
- **To install use:**
        conda install numpy

In [2]:
import numpy as np

### Numpy arrays have two forms: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating numpy arrays:
- **From a Python List**
- **Built-in ways to create Arrays**
    - **arange: for evenly spaced values within a given interval**
    - **zeros and ones:  arrays of zeros or ones**
    - **np.full: Return a new array of given shape and type, filled with fill_value.**
    - **np.repeat:Repeat elements of an array**
    - **linspace: evenly spaced numbers over a specified interval**
    - **eye: for an identity matrix**
- **Random: create random number arrays**
    - **rand: For creating array of the given shape and fill it with random samples from a uniform distribution over ``[0, 1)``**
    - **randn: creates a sample (or samples) from the "standard normal" distribution. rand is uniform distribution**
    - **randint: Creates random integers from low (inclusive) to high (exclusive). Assigning `step` parameter is possible**
    

## Methods and Attributes:
- **reshape: returns array with same data but with a new shape**
- **max,min,argmax,argmin: Methods for finding max or min values or to find their index locations using argmin or argmax**
- **shape: to know the shape of array**
- **dtype: to know the data type of the object in the array**


In [3]:
list1 = [5,5,6,7,8,5,2,5]
list1

[5, 5, 6, 7, 8, 5, 2, 5]

In [4]:
np.array(list1)

array([5, 5, 6, 7, 8, 5, 2, 5])

In [5]:
matrix1 = [[8,9,5.2],[5,161,2],[846,2,8]]
matrix1

[[8, 9, 5.2], [5, 161, 2], [846, 2, 8]]

In [6]:
np.array(matrix1)

array([[  8. ,   9. ,   5.2],
       [  5. , 161. ,   2. ],
       [846. ,   2. ,   8. ]])

### Built-in ways to create Arrays
### arange: for evenly spaced values within a given interval

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

### np.zeros and np.ones: arrays of zeros or ones
### np.full: Return a new array of given shape and type, filled with fill_value.
### np.repeat:Repeat elements of an array

In [9]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [15]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

### linspace: evenly spaced numbers over a specified interval

In [16]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [17]:
np.linspace(0,30,50)

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

## eye: for an identity matrix

In [19]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## Random: create random number arrays
### rand:
  - **For creating array of the given shape and fill it with random samples from a uniform distribution over [0, 1)**

In [20]:
np.random.rand(5)

array([0.09524311, 0.53192916, 0.94615572, 0.07177538, 0.84266036])

In [30]:
np.random.rand(7,5) 

array([[0.82895284, 0.44846154, 0.80614937, 0.44703266, 0.65421724],
       [0.05134697, 0.92760642, 0.95216865, 0.0882743 , 0.11187308],
       [0.49335516, 0.56382287, 0.90893139, 0.78005033, 0.26949719],
       [0.24358496, 0.54923545, 0.70248039, 0.92734818, 0.78514931],
       [0.45952209, 0.34173968, 0.28676544, 0.40456481, 0.46072349],
       [0.6685776 , 0.74063267, 0.03126001, 0.93268167, 0.29635339],
       [0.69439528, 0.93089371, 0.17060994, 0.34207331, 0.6064884 ]])

### randn: 
- **creates a sample (or samples) from the "standard normal" distribution. rand is uniform distribution**

In [31]:
np.random.randn(5)

array([-0.18748486, -0.30695943,  1.12441369, -0.49053392,  0.97733461])

In [33]:
np.random.randn(7,5)

array([[-0.27287727, -1.20403272, -1.68426358, -1.72489613, -0.95470347],
       [-1.22310417,  0.03381994,  1.76558787,  0.07953593, -1.33919605],
       [ 0.89669165,  0.64068341,  0.56449662,  0.90118055,  0.37732863],
       [ 1.39693743,  0.7676323 , -0.35819089, -0.80611744, -0.67837097],
       [ 0.59510482, -0.41766808,  0.14719214,  1.23676988,  0.87713345],
       [-1.05225279, -0.77290492, -1.2287601 , -0.11307159,  1.09152525],
       [ 1.00428597, -0.92076225,  0.65284887, -1.06410431,  0.20737464]])

### randint: 
- **Creates random integers from low (inclusive) to high (exclusive). Assigning step parameter is possible**

In [35]:
np.random.randint(1,500)

441

In [36]:
np.random.randint(1,500,10)

array([334, 443,  71, 254, 134,   6, 362, 147, 373,  82])

## Methods and Attributes:
### reshape: 
- **returns array with same data but with a new shape**

In [45]:
arr = np.arange(30)
ranarr = np.random.randint(0,500,10)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
ranarr

array([205, 285, 310, 493, 244, 101, 272, 142, 448, 327])

### Reshape
- **Returns an array containing the same data with a new shape.**


In [49]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### max,min,argmax,argmin
- **These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax**


In [50]:
ranarr

array([205, 285, 310, 493, 244, 101, 272, 142, 448, 327])

In [51]:
ranarr.max()

493

In [52]:
ranarr.argmax()

3

In [53]:
ranarr.min()

101

In [54]:
ranarr.argmin()

5

### Shape
- **to know the shape of array**


In [56]:
# Vector
arr.shape

(30,)

In [58]:
# Notice the two sets of brackets
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
arr.reshape(1,30).shape

(1, 30)

In [60]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [62]:
arr.reshape(30,1).shape

(30, 1)

### dtype
- **You can also grab the data type of the object in the array**

In [63]:
arr.dtype

dtype('int32')

## Accessing the element of an array by index:


In [66]:
el = array[1]
print(el)

0.0


## Accessing multuple elements of an array by a list of indices:


In [67]:
array[[4, 2, 0]]

array([1., 1., 0.])

## Assignment:

In [68]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


## Multi-dimensional NumPy arrays
### Specify the shape with a tuple:

In [71]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [72]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [73]:
print(numbers[0, 1])

2


## Assignment: use a tuple (row index, column index)

In [74]:
numbers[0, 1] = 10

In [75]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [76]:
numbers[0]

array([ 1, 10,  3])

## Slicing: getting a column:

In [77]:
numbers[:, 1]

array([10,  5,  8])

## Assigning a row:

In [78]:
numbers[1] = [1, 1, 1]
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

## Assigning a column:

In [79]:
numbers[:, 2] = [9, 9, 9]
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

# Element-wise operations

In [80]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

## Every item in the array is multiplied by 2: 

In [81]:
rng * 2

array([0, 2, 4, 6, 8])

In [82]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

## Adding one array with another

In [83]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [84]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [85]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

## Rounding the numbers to 4th digit:


In [86]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

## Two ways to square each element:
- element-wise multiplication with itself**
- the power operator (**)

In [87]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [88]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [89]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

## Other element-wise operations:

    exp
    log
    sqrt



In [91]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [92]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [93]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

# Comparison operations

In [94]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [95]:
result = pred >= 0.5
result

array([False, False,  True])

In [97]:
np.random.seed(2)
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [98]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [100]:
pred1 >= pred2

array([ True, False,  True])

# Logical operations

In [104]:
pred1 = np.random.rand(3) >= 0.3
pred2 = np.random.rand(3) >= 0.4

In [105]:
pred1 & pred2

array([False,  True, False])

In [106]:
pred1 | pred2

array([False,  True,  True])

# Summarizing operations
- **Summarizing operations process and array and return a single number**

In [110]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [109]:
pred_sum

1.02

In [111]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


## For two-dimentional array it works in the same way:


In [112]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [113]:
matrix.max()

0.62

## But we can specify the axis along which we apply the summarizing operation
- **axis=1 - apply to each rows**
- **axis=0 - apply to each column**



In [115]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [116]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [117]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

# Sorting

In [118]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [120]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [121]:
pred

array([0.44, 0.03, 0.55, 0.44])

## Sorts in place:

In [122]:
pred.sort()

In [123]:
pred

array([0.03, 0.44, 0.44, 0.55])

## Argsort - instead of sorting, return the indexes of the array in sorted order

In [124]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [125]:
idx = pred.argsort()

In [126]:
idx

array([1, 0, 3, 2], dtype=int64)

In [127]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

## Putting mulitple arrays together:
- **concatenate**
- **hstack : Stack arrays in sequence horizontally (column wise).**
- **vstack: Stack arrays in sequence vertically (row wise).**
- **column_stack: Stack 1-D arrays as columns into a 2-D array.**



In [129]:
vec = np.arange(3)
vec


array([0, 1, 2])

In [132]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [133]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [134]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [135]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [136]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [138]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [139]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [141]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [142]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

# Transpose

In [143]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [145]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

# Slicing
- Taking a part of the array


In [146]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [147]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [149]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [150]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [151]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [153]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [154]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])