In [1]:
import numpy as np

In [14]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

- The **dot product** or also known as the **scalar product** is an algebraic operation that takes **two equal-length sequences** of numbers and returns a single number. 
- Let us consider given two vectors A and B, and we have to find the dot product of two vectors.

- Given that, 

#### A = $a_1i + a_2j + a_3k$ and

#### B = $b_1i + b_2j + b_3k$

    Where,

    i: the unit vector along the x directions

    j: the unit vector along the y directions

    k: the unit vector along the z directions

### Then the dot product is calculated as:
## DotProduct = $a_1 * b_1 + a_2 * b_2 + a_3 * b_3$
 


## Implementing dot product without using numpy
- **assert:** The Python assert keyword tests if a condition is true. If a condition is false, the program will stop with an optional message. Assert statements are used to debug code and handle errors. You should not use an assert statement in a production environment.

In [6]:
def vec_vec_multiplication(u,v):
    assert u.shape[0] == v.shape[0]   # Checking if the shape of u and v vectors are same
    n = u.shape[0]                    # declaring number of times our for loop should run == number of rows. 
                                      # Since both rows same, we can use any of u or v
    result = 0.0                      # Declaring the variable called result.
    for i in range(n):                # Creating a for loop to multiply components of u and v
        result += u[i]*v[i]           # Adding the result to take care of the addition step of Dot Product
    return result

vec_vec_multiplication(u,v)           # Checking the function on two vectors u and v 

14.0

## Dot product using numpy

- Python provides a very efficient method to calculate the dot product of two vectors. 
- By using numpy.dot() method which is available in the NumPy module one can do so.
    
### Syntax:

- numpy.dot(vector_a, vector_b, out = None)

### Parameters:
- vector_a: [array_like] if a is complex its complex conjugate is used for the calculation of the dot product.
- vector_b: [array_like] if b is complex its complex conjugate is used for the calculation of the dot product.
- out: [array, optional] output argument must be C-contiguous, and its dtype must be the dtype that would be returned for dot(a,b).

### Return:
- Dot Product of vectors a and b. if vector_a and vector_b are 1D, then scalar is returned

In [8]:
u.dot(v)

14

## Matrix and Vector dot product 


In [22]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

U.shape

(3, 4)

### Matrix-Vector Multiplication (Dot Product) implementation

In [18]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]                         # Checking the condition that num of cols in U == num of rows in v
    
    num_rows = U.shape[0]                                   # Creating a variable for number of rows, loop runs these many times
    resultant_vector = np.zeros(num_rows)                   # Creating an array of zeros with num of rows = final vector
    
    for i in range(num_rows):                               # Looping over the num_rows
        resultant_vector[i] = vec_vec_multiplication(U[i],v)# using Dot product formula: Ui*vi
    return resultant_vector     

matrix_vector_multiplication(U, v)                          # calling the function of Matrix U and vector v



array([14.,  5.,  5.])

### Dot product using numpy

In [19]:
U.dot(v)

array([14,  5,  5])

## Matrix-Matrix Multiplication (Dot Product) implementation

In [20]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [23]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]               # Checking the condition that num of cols in U == num of rows in v
    
    num_rows = U.shape[0]                         # Creating a variable for number of rows, loop runs from here
    num_cols = V.shape[1]                         # Creating a variable for number of cols, loop runs till here.
    
    resutant_matrix = np.zeros((num_rows, num_cols)) # Creating an array of zeros with num of rows = final vector
    
    for i in range(num_cols):
        vi = V[:,i]                               # Need to multiply U*V0 for the first column, hence creating Vi to generalize
        Uvi = matrix_vector_multiplication(U,vi)  # Performing Matrix(U) and vector(vi)
        resutant_matrix[:, i] = Uvi               # Updating columns in the zeros matrix created outside the loop.
    
    return resutant_matrix


matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Using numpy to perform dot product of two matrix

In [24]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [25]:
I = np.eye(3)

In [26]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse:
### The concept of inverse of a matrix is a multidimensional generalization of the concept of reciprocal of a number:
- **the product between a number and its reciprocal is equal to 1;**
- **the product between a square matrix and its inverse is equal to the identity matrix.**

## Inverse of matrix using numpy
### np.linalg.inv() 
- **Compute the (multiplicative) inverse of a matrix.**

In [27]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [28]:
Vs_inv = np.linalg.inv(Vs) 
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [29]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])